### ISSUE TITLE
Incorrect syntax near the keyword 'INTO'

### ISSUE THREAD

**Issue by ccrookston** [KostovMartin/Dapper.Bulk#10]
Hello!

I'm using Dapper.Bulk to attempt a bulk insert.  I get this error message:

System.Data.SqlClient.SqlException: Incorrect syntax near the keyword 'INTO'.\r\nIncorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.

Here's the actual code:

    using (SqlConnection conn = new SqlConnection(...))
    {
        conn.BulkInsert(translationPhraseList);
    }

'translationPhraseList' is a `List<PETranslationPhrase>`.  And here's `PETranslationPhrase`, which is an auto-generated class from a ModelGenerator.tt file:

    /// <summary>
    /// A class which represents the PE_TranslationPhrase table.
    /// </summary>
	[Table("PE_TranslationPhrase")]
	public partial class PETranslationPhrase
	{
		[Key]
		public virtual int TranslationId { get; set; }
		public virtual string CultureName { get; set; }
		public virtual string Phrase { get; set; }
		public virtual Guid? PhraseHash { get; set; }
		public virtual DateTime RowAddedDateTime { get; set; }
	}

Am I doing something wrong? Or is this a bug in Dapper.Bulk?

**Comment by KostovMartin** [comment]
Hello,

The issue is in the library. 
I've created new hot-fix version 1.4.2, which should add support for Guids.

Martin

**Comment by andrea-spotsoftware** [comment]
I'm still having this issue with 1.4.2 version.
