### ISSUE TITLE
Bulk insert doesn't support byte[] datatype

### ISSUE THREAD

**Issue by Nimrodinho** [KostovMartin/Dapper.Bulk#16]
Hi,

we have varbinary column in our database which we are trying to insert using BulkInsert method.
Field is not registered as a valid property due to ValidateProperty which excludes it.

Potential fix would be to add another OR condition in ValidateProperty method for byte[] in line 48 (PropertyCache.cs)

result = result && (!prop.PropertyType.IsClass || prop.PropertyType == typeof(string) || prop.PropertyType == typeof(byte[]));

**Comment by KostovMartin** [comment]
Can you create PR with the change?

**Comment by snkline** [comment]
I have added a PR with this change.

https://github.com/KostovMartin/Dapper.Bulk/pull/20

**Comment by KostovMartin** [comment]
Support is added in [version 1.5](https://github.com/KostovMartin/Dapper.Bulk/releases/tag).
