### ISSUE TITLE
Bulk insert doesn't support non autoincrement Id column 

### ISSUE THREAD

**Issue by mennansevim** [KostovMartin/Dapper.Bulk#17]
Cannot insert the value NULL into column 'Id' without autoincrement id

when trying to give a value to id it gives a "cannot insert null value to id" error, 
although I should be able to give a value on non auto increment id column

**Comment by KostovMartin** [comment]
Support is added in [version 1.5](https://github.com/KostovMartin/Dapper.Bulk/releases/tag/v1.5.0).
