### ISSUE TITLE
Temporary table creation fails with System.Data.SqlClient.SqlException when table name includes schema name

### ISSUE THREAD

**Issue by mullerc** [KostovMartin/Dapper.Bulk#2]
Hi Martin

Really useful extension to Dapper - thanks. I have identified the issue above and fixed it in my fork.

Table: MySchema.CorpDate
No attributes on model class (CorpDate)
`TableMapper.SetupConvention("MySchema.", string.Empty);`

When the table name includes a schema name e.g. **MySchema.CorpDate** the SQL to create the temporary table is:

`SELECT TOP 0 [Day], [Week] INTO #MySchema.CorpDate_TempInsert FROM MySchema.CorpDate target WITH(NOLOCK);`

This gives the following error as SQL Server is looking for a schema named **#MySchema** and not **MySchema**:

_Message=The specified schema name "#MySchema" either does not exist or you do not have permission to use it._

I have changed BulkInsertAsync in DapperBulk.cs in my fork so that the "." is removed from the temporary table name so that SQL Server no longer looks for a schema called **#MySchema**. The temporary table name is now **#MySchemaCorpDate_TempInsert**

`var tempToBeInserted = $"#{tableName}_TempInsert".Replace(".", string.Empty);`

I believe tempInsertedWithIdentity in other methods may need this change also but I haven't tested that yet.

Would you like me to create a pull request?

Cheers
Col

**Comment by KostovMartin** [comment]
Hello,

Yes please create pull request.
I will check it in the next few days.

Regards,
Martin
