### ISSUE TITLE
System.Data.Client does not support Azure AD

### ISSUE THREAD

**Issue by markhoratiowalmsley** [KostovMartin/Dapper.Bulk#22]
The current version uses System.Data.Client, rather than Microsoft.Data.SqlClient, this means that the newer AD functionality can't be used alongside this library:
https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-aad-overview]]

I've pulled the code and replaced System.Data.Client with Microsoft.Data.SqlClient and everything works fine so it would be good if Microsoft.Data.SqlClient could be used instead.

**Comment by ismamad** [comment]
Also would like to see this update happening in this package.
