### ISSUE TITLE
TableAttribute.Schema property is ignored

### ISSUE THREAD

**Issue by SomeoneIsWorking** [KostovMartin/Dapper.Bulk#23]
`Dapper.Bulk` expects schema name to be in `TableAttribute.Name` property such as `[Table("<schema>.<table-name>")]`
But completely ignores `TableAttribute.Schema` property
And I also use `Dapper.SimpleCRUD` which uses `TableAttribute.Schema` property and doesn't work if schema is in the table name

**Comment by needo2** [comment]
Dapper also automatically opens and closes connection if it wasn't open before but this library doesn't do it
Also no reason nullables shouldn't be supported
