### ISSUE TITLE
How to use with MySQL

### ISSUE THREAD

**Issue by tech-a-go-go** [KostovMartin/Dapper.Bulk#6]
Hi there,

I'm stuck on using Dapper.Bulk with MySQL.
MySQL library provides a MySqlConnection object but it is derived from System.Data.Common.DBConnection not System.Data.SqlClient.SqlConnection so it's not compatible with Dapper.Bulk.

Are there any ways to use Dapper.Bulk with MySQL connection ??

Cheers

**Comment by KostovMartin** [comment]
Hi,
Currently it only supports MSSQL Server, other DBs are not supported.
