### ISSUE TITLE
Weird Table Names

### ISSUE THREAD

**Issue by brunotourinho** [KostovMartin/Dapper.Bulk#7]
Hi! First of all, thanks for sharing your work!

I'm trying to bulkinsert async to a Table named "05_BENEFICIARIOS".

`await ((SqlConnection) db).BulkInsertAsync(list);`

 I'm getting the following error:

Incorrect syntax near '05_BENEFICIARIOS'.
Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.

 I don't know what I'm doing wrong.

**Comment by KostovMartin** [comment]
The issue was fixed in [v1.4.1](https://github.com/KostovMartin/Dapper.Bulk/tree/v1.4.1).

**Comment by brunotourinho** [comment]
WOW! So fast! 
Thank You!

**Comment by brunotourinho** [comment]
Hey Martin! Sorry to bug you again... now the message changed...

Incorrect syntax near '05_BENEFICIARIOS'.
Unclosed quotation mark after the character string '[05_BENEFICIARIOS] target WITH(NOLOCK);'.

**Comment by KostovMartin** [comment]
Can you send me the exact Table attribute usage.

**Comment by brunotourinho** [comment]
Sure, the code goes as follows: 

`[Table("[05_BENEFICIARIOS]")]
    public class Beneficiario
    {
        [Key]
        public int Id { get; set; }
...`

**Comment by KostovMartin** [comment]
Try without [] only "05_BENEFICIARIOS", with next version we will fix that as well.

**Comment by brunotourinho** [comment]
Worked as a charm! Thank you!
